# Test bibd configuration
server:
  data_dir: "./test_data"
  log_level: "debug"

database:
  backend: postgres
  postgres:
    managed: true
    network:
      use_unix_socket: false
      bind_address: "127.0.0.1"

